CREATE DATABASE Pizza;

USE Pizza;

 --all records from the orders table
SELECT *
FROM orders;

--all records from the order_details table
SELECT *
FROM order_details;

--joining the orders table with the order_details table
SELECT orders.order_id,date,time,order_details_id,pizza_id,quantity
FROM orders
LEFT JOIN order_details 
on orders.order_id = order_details.order_id;

--all records from the pizza's table
SELECT *
FROM pizzas;

--all records from the pizza_types table
SELECT *
FROM pizza_types;

--joining the pizzas table with the pizza_types table
SELECT *
FROM pizzas
LEFT JOIN pizza_types 
on pizzas.pizza_type_id = pizza_types.pizza_type_id;


--joining all four tables together
SELECT orders.order_id, date, time, order_details_id, order_details.pizza_id, quantity, pizzas.pizza_type_id, size, price, name, category, ingredients
FROM orders
LEFT JOIN order_details 
ON orders.order_id = order_details.order_id
LEFT JOIN pizzas
ON order_details.pizza_id = pizzas.pizza_id
LEFT JOIN pizza_types
ON pizzas.pizza_type_id = pizza_types.pizza_type_id;

--creating a new table that contains all the columns in the above join.
CREATE TABLE Pizza_Restaurant(
order_id SMALLINT, 
date DATE, 
time DATETIME, 
order_details_id BIGINT,
pizza_id NVARCHAR(50), 
quantity TINYINT,
pizza_type_id NVARCHAR(50), 
size NVARCHAR(50), 
price FLOAT, 
name NVARCHAR(50), 
category NVARCHAR(50), 
ingredients NVARCHAR (100));

--Moving the output from the joined table to the new table "Pizza_Restaurant"
INSERT INTO Pizza_Restaurant
SELECT orders.order_id, date, time, order_details_id, order_details.pizza_id, quantity, pizzas.pizza_type_id, size, price, name, category, ingredients
FROM orders
LEFT JOIN order_details 
ON orders.order_id = order_details.order_id
LEFT JOIN pizzas
ON order_details.pizza_id = pizzas.pizza_id
LEFT JOIN pizza_types
ON pizzas.pizza_type_id = pizza_types.pizza_type_id;

--selecting all records from Pizza_Restaurant table to check output
SELECT * FROM Pizza_Restaurant;

--finding the unique combined ingredients
SELECT DISTINCT (ingredients) as Combos, name
FROM Pizza_Restaurant;

--Names of pizzas
SELECT DISTINCT (name)
FROM Pizza_Restaurant;

--count of quantity based on pizza type 
SELECT COUNT (quantity) as count_of_quantity, name, ingredients
FROM Pizza_Restaurant
GROUP BY ingredients, name
ORDER BY count_of_quantity;

--total quantity of pizzas ordered in the year
SELECT sum(quantity) as sum_of_quantity
FROM Pizza_Restaurant;

--TEN most ordered pizza
SELECT TOP 10 COUNT (quantity) as count_of_quantity, name, ingredients
FROM Pizza_Restaurant
GROUP BY ingredients, name
ORDER BY count_of_quantity DESC;

--TEN least ordered pizza
SELECT TOP 10 COUNT (quantity) as count_of_quantity, name, ingredients
FROM Pizza_Restaurant
GROUP BY ingredients, name
ORDER BY count_of_quantity ASC;

--count of quantity ordered all year round grouped by category
SELECT COUNT (quantity) as count_of_quantity, category
FROM Pizza_Restaurant
GROUP BY category
ORDER BY count_of_quantity DESC;

--total amount generated by category
SELECT sum (price) as total_price_by_category, category
FROM Pizza_Restaurant
GROUP BY category
ORDER BY total_price_by_category DESC;

--amount generated by each pizza type in the year
SELECT SUM (price) as total_amount_spent, name
FROM Pizza_Restaurant
GROUP BY name
ORDER BY total_amount_spent DESC;

--pizza type that generated the most revenue for the restaurant -- pizzas ordered the most were not necessarily the ones bringing in most of 
--the revenue
SELECT TOP 10 SUM (price) as total_amount_spent, name
FROM Pizza_Restaurant
GROUP BY name
ORDER BY total_amount_spent DESC;

--pizza types that generated the least revenue for the company
SELECT TOP 10 SUM (price) as total_amount_spent, name
FROM Pizza_Restaurant
GROUP BY name
ORDER BY total_amount_spent ASC;

--Analysis by month
SELECT sum(price) as amount_generated_by_months
FROM Pizza_Restaurant
WHERE date BETWEEN '2015-12-01' and '2015-12-31';

SELECT*
FROM Pizza_Restaurant;

--count of pizzas ordered the most size wise
SELECT COUNT (quantity) as count_of_quantity, pizza_id, price, name
FROM Pizza_Restaurant
GROUP BY pizza_id, price, name
ORDER BY count_of_quantity DESC;

--most ordered sizes of pizza
SELECT TOP 10 COUNT (quantity) as count_of_quantity, pizza_id, price, name
FROM Pizza_Restaurant
GROUP BY pizza_id, price, name
ORDER BY count_of_quantity DESC;

-- least ordered sizes
SELECT TOP 10 COUNT (quantity) as count_of_quantity, pizza_id, price, name
FROM Pizza_Restaurant
GROUP BY pizza_id, price, name
ORDER BY count_of_quantity ASC;

--Cheapest pizzas
SELECT TOP 10 price as cheapest_pizzas, pizza_id, name
FROM Pizza_Restaurant
GROUP BY pizza_id, price, name
ORDER BY cheapest_pizzas ASC;

--Most expensive pizzas in descending order
SELECT TOP 10 price as most_expensive_pizzas, count(order_details_id) as quantity_ordered, pizza_id, name
FROM Pizza_Restaurant
GROUP BY pizza_id, price, name
ORDER BY most_expensive_pizzas DESC;

USE Pizza;
SELECT* FROM Pizza_Restaurant

